App
jonathastavares/React-To-Do pull request #1
Opened 2021-11-02 01:11 UTC by jonathastavares

In this milestone I created a simple Todo app with the following features:
- Add item function
- Delete item function
- Edit item function
- Homepage
- About page

Built with:
- React
- JavaScript
- HTML
- CSS

2021-11-03 12:10 UTC, ahmedadel56 commented
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
- [ ] I can see you have not completed the project. Please request a review after you feel the project needs a proper review because you have a limited number of reviews. 
<img width="894" alt="Capture" src="https://user-images.githubusercontent.com/58504655/133367422-69272f9d-6a87-4bef-a1f0-6b6a5202d7e7.PNG">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-11-03 12:16 UTC, ahmedadel56 requested changes

2021-11-03 12:16 UTC, ahmedadel56 commented on src/functionBased/components/Navbar.js
> +/* eslint-disable react/button-has-type */
Please Remove that line and try to solve the linter error

2021-11-03 12:16 UTC, ahmedadel56 commented on src/functionBased/components/TodoContainer.js
> +/* eslint-disable no-use-before-define, no-param-reassign */
As here too, you should fix the linter error instead of disabling it

2021-11-03 12:16 UTC, ahmedadel56 commented on README.md
> +- GitHub: [jonathastavares](https://github.com/jonathastavares)
please try to pass the readme file to Grammarly to check grammar problems

2022-01-11 18:58 UTC, ShadyShawkat commented
# Hi @jonathastavares, 👋🏻  

You have done awesome work so far, and it shows! 🔥 🚀 
I don't have any major change for you as of right now.

## Optional suggestions

- You can add a live demo link in your README.md file, which makes it easier to access your project.
- An image in your README.md file would be awesome to better showcase the look of your project.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-01-12 12:44 UTC, merged